name: Minecraft Server

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start Minecraft server
      run: |
        java -Xmx1024M -Xms1024M -jar server.jar nogui
