name: Minecraft Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Build and start Minecraft server
      run: |
        java -Xmx1024M -Xms1024M -jar server.jar nogui

    - name: Get server IP address
      run: |
        server_ip=$(curl -s ifconfig.co)
        echo "Server IP address: $server_ip"
